# Generated by Django 5.2.6 on 2026-01-03 08:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True)),
                ('file_pdf', models.FileField(upload_to='artikel_pdf/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kuis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('youtube_id', models.CharField(max_length=20)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pertanyaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks', models.CharField(max_length=255)),
                ('kuis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pertanyaan', to='konten.kuis')),
            ],
        ),
        migrations.CreateModel(
            name='Opsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks_opsi', models.CharField(max_length=255)),
                ('is_benar', models.BooleanField(default=False)),
                ('pertanyaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opsi', to='konten.pertanyaan')),
            ],
        ),
    ]
