# Generated by Django 5.2.6 on 2026-01-03 08:17

import django.core.validators
import konten.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konten', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='file_pdf',
            field=models.FileField(upload_to=konten.models.artikel_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
