# Generated by Django 5.2.6 on 2026-01-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konten', '0002_alter_artikel_file_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
