# Generated by Django 5.2.6 on 2026-01-03 09:17

import konten.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konten', '0003_artikel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikel',
            name='slug',
        ),
        migrations.AlterField(
            model_name='artikel',
            name='file_pdf',
            field=models.FileField(upload_to=konten.models.artikel_upload_path),
        ),
        migrations.AlterField(
            model_name='pertanyaan',
            name='teks',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(max_length=50),
        ),
    ]
