# Generated by Django 5.2.6 on 2026-01-06 03:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konten', '0004_remove_artikel_slug_alter_artikel_file_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='file_pdf',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
