# Generated by Django 5.1.4 on 2025-11-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_kelas_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('guru', 'gurubk'), ('siswa', 'Siswa')], default='siswa', max_length=20),
        ),
    ]
