# Generated by Django 5.1.4 on 2025-11-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('siswa', 'Siswa'), ('guru_bk', 'gurubk'), ('admin', 'Admin')], default='siswa', max_length=20),
        ),
    ]
