# Generated by Django 5.1.4 on 2025-12-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nis',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
