# Generated by Django 5.1.4 on 2025-12-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_force_password_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tanggal_akhir_aktif',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tanggal_masuk',
            field=models.DateField(blank=True, null=True),
        ),
    ]
