# Generated by Django 5.2.6 on 2026-01-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_tanggal_akhir_aktif_profile_tanggal_masuk'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='kelas_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='kelas',
            field=models.CharField(blank=True, choices=[('VII A', 'VII A'), ('VII B', 'VII B'), ('VII C', 'VII C'), ('VII D', 'VII D'), ('VII E', 'VII E'), ('VIII A', 'VIII A'), ('VIII B', 'VIII B'), ('VIII C', 'VIII C'), ('VIII D', 'VIII D'), ('VIII E', 'VIII E'), ('IX A', 'IX A'), ('IX B', 'IX B'), ('IX C', 'IX C'), ('IX D', 'IX D'), ('IX E', 'IX E')], max_length=10, null=True),
        ),
    ]
