# Generated by Django 5.2.6 on 2026-01-11 10:00

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_anonymous', models.BooleanField(default=False, help_text='Jika dicentang, identitas pelapor disembunyikan di tampilan')),
                ('nama_korban', models.CharField(help_text='Nama korban perundungan', max_length=100)),
                ('kelas_korban', models.CharField(help_text='Kelas korban', max_length=10)),
                ('nama_terlapor', models.CharField(blank=True, max_length=100, null=True)),
                ('kelas_terlapor', models.CharField(blank=True, max_length=10, null=True)),
                ('jenis_bullying', models.CharField(choices=[('verbal', 'Verbal'), ('fisik', 'Fisik'), ('sosial', 'Sosial'), ('siber', 'Siber'), ('psikologis', 'Psikologis'), ('lainnya', 'Lainnya')], max_length=20)),
                ('isi_laporan', models.TextField(help_text='Kronologi kejadian bullying')),
                ('bukti', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('baru', 'Laporan Baru'), ('diproses', 'Sedang Diproses'), ('selesai', 'Selesai Ditangani')], default='baru', max_length=20)),
                ('catatan_bk', models.TextField(blank=True, help_text='Catatan internal Guru BK', null=True)),
                ('bukti_tindak_lanjut', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('kode_laporan', models.CharField(max_length=12, unique=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('pelapor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan_bullying', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
