# Generated by Django 5.2.6 on 2026-01-03 03:19

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelapor', models.CharField(max_length=100)),
                ('nis_pelapor', models.CharField(max_length=20)),
                ('kelas_pelapor', models.CharField(max_length=20)),
                ('terlapor', models.CharField(max_length=100)),
                ('jenis_bullying', models.CharField(choices=[('Fisik', 'Bullying Fisik (memukul, mendorong, dll)'), ('Verbal', 'Bullying Verbal (mengejek, menghina, dll)'), ('Sosial', 'Bullying Sosial (mengucilkan, menyebarkan gosip)'), ('Cyber', 'Cyberbullying (media sosial / online)')], max_length=20)),
                ('isi_laporan', models.TextField()),
                ('bukti', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='bukti_laporan')),
                ('status', models.CharField(default='Menunggu Ditindaklanjuti', max_length=50)),
                ('catatan_bk', models.TextField(blank=True, null=True)),
                ('bukti_tindak_lanjut', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='tindak_lanjut')),
                ('kode_laporan', models.CharField(max_length=12, unique=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
