# Generated by Django 5.2.6 on 2026-01-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporan',
            name='jenis_bullying',
            field=models.CharField(choices=[('Fisik', 'Bullying Fisik'), ('Verbal', 'Bullying Verbal'), ('Sosial', 'Bullying Sosial'), ('Cyber', 'Cyberbullying')], max_length=20),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='kelas_pelapor',
            field=models.CharField(choices=[('VII A', 'VII A'), ('VII B', 'VII B'), ('VII C', 'VII C'), ('VII D', 'VII D'), ('VII E', 'VII E'), ('VIII A', 'VIII A'), ('VIII B', 'VIII B'), ('VIII C', 'VIII C'), ('VIII D', 'VIII D'), ('VIII E', 'VIII E'), ('IX A', 'IX A'), ('IX B', 'IX B'), ('IX C', 'IX C'), ('IX D', 'IX D'), ('IX E', 'IX E')], max_length=10),
        ),
    ]
