# Generated by Django 5.2.6 on 2026-01-03 09:48

import laporan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporan',
            name='bukti',
            field=models.FileField(blank=True, null=True, upload_to='laporan_bukti/', validators=[laporan.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='bukti_tindak_lanjut',
            field=models.FileField(blank=True, null=True, upload_to='laporan_tindak_lanjut/', validators=[laporan.models.validate_file_size]),
        ),
    ]
