# Generated by Django 5.2.6 on 2026-01-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0002_alter_laporan_jenis_bullying_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporan',
            name='status',
            field=models.CharField(
                max_length=50,
                choices=[
                    ('baru', 'Laporan Baru'),
                    ('diproses', 'Sedang Diproses'),
                    ('selesai', 'Selesai Ditangani'),
                ],
                default='baru',
            ),
        ),
    ]
