# Generated by Django 5.2.6 on 2026-01-06 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0003_alter_laporan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporan',
            name='status',
            field=models.CharField(choices=[('baru', 'Laporan Baru'), ('diproses', 'Sedang Diproses'), ('selesai', 'Selesai Ditangani')], default='baru', max_length=50),
        ),
    ]
