# Generated by Django 5.2.6 on 2026-01-06 03:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0004_alter_laporan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporan',
            name='bukti',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='bukti_tindak_lanjut',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
