# Generated by Django 5.2.6 on 2026-01-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0004_recreate_laporan_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='dampak_korban',
            field=models.JSONField(blank=True, help_text='Daftar dampak yang dirasakan korban', null=True),
        ),
        migrations.AddField(
            model_name='laporan',
            name='dampak_lainnya',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laporan',
            name='harapan_pelapor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laporan',
            name='lokasi_kejadian',
            field=models.CharField(blank=True, help_text='Lokasi kejadian bullying', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laporan',
            name='perkiraan_waktu',
            field=models.CharField(blank=True, choices=[('pagi', 'Pagi'), ('siang', 'Siang'), ('sore', 'Sore')], help_text='Perkiraan waktu kejadian', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='laporan',
            name='pernyataan_setuju',
            field=models.BooleanField(default=False, help_text='Pernyataan bahwa laporan dibuat dengan jujur'),
        ),
        migrations.AddField(
            model_name='laporan',
            name='tanggal_kejadian',
            field=models.DateField(blank=True, help_text='Tanggal terjadinya perundungan', null=True),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='Jika dicentang, identitas pelapor disembunyikan'),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='isi_laporan',
            field=models.TextField(help_text='Kronologi kejadian bullying'),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='jenis_bullying',
            field=models.CharField(choices=[('verbal', 'Verbal'), ('fisik', 'Fisik'), ('sosial', 'Sosial'), ('siber', 'Siber'), ('psikologis', 'Psikologis'), ('lainnya', 'Lainnya')], max_length=20),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='kelas_korban',
            field=models.CharField(choices=[('VII A', 'VII A'), ('VII B', 'VII B'), ('VII C', 'VII C'), ('VII D', 'VII D'), ('VII E', 'VII E'), ('VIII A', 'VIII A'), ('VIII B', 'VIII B'), ('VIII C', 'VIII C'), ('VIII D', 'VIII D'), ('VIII E', 'VIII E'), ('IX A', 'IX A'), ('IX B', 'IX B'), ('IX C', 'IX C'), ('IX D', 'IX D'), ('IX E', 'IX E')], max_length=10),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='status',
            field=models.CharField(choices=[('baru', 'Laporan Baru'), ('diproses', 'Sedang Diproses'), ('selesai', 'Selesai Ditangani')], default='baru', max_length=20),
        ),
    ]
