# Generated by Django 5.2.6 on 2026-02-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0005_laporan_dampak_korban_laporan_dampak_lainnya_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='is_korban_anonim',
            field=models.BooleanField(default=False, help_text='Jika dicentang, identitas korban disembunyikan'),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='dampak_korban',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='lokasi_kejadian',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='perkiraan_waktu',
            field=models.CharField(blank=True, choices=[('pagi', 'Pagi'), ('siang', 'Siang'), ('sore', 'Sore')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='pernyataan_setuju',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='tanggal_kejadian',
            field=models.DateField(blank=True, null=True),
        ),
    ]
